/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author joshu
 */
import javax.swing.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public final class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    //The below map is used to easily link the name used in the JComboBox, to a project
    private Map<String, Project> projects = new HashMap<String, Project>();
    //Example: projects.put(project.getName(), project);
    private ArrayList<String> projectNames = new ArrayList<>();
    public MainForm() {
        super("Admin panel");
        Project project1 = new Project("proj1 title");
        addProjectToList(project1);
        Project project2 = new Project("proj2 title");
        addProjectToList(project2);
        Project project3 = new Project("proj3 title");
        addProjectToList(project3);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        };
        initComponents();
        funcvisible();
    }
    public void addProjectToList(Project proj){
        projects.put(proj.getName(), proj);
        projectNames.add(proj.getName());
    }
    public void funcvisible() {
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        createProjectButton = new javax.swing.JButton();
        deleteProjectButton = new javax.swing.JButton();
        projectList = new javax.swing.JComboBox<>();
        createTeamButton = new javax.swing.JButton();
        deleteTeamButton = new javax.swing.JButton();
        teamList = new javax.swing.JComboBox<>();
        manageProjectButton = new javax.swing.JButton();
        projectListLabel = new javax.swing.JLabel();
        teamListLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createProjectButton.setText("Create Project");
        createProjectButton.addActionListener(evt -> createProjectButtonActionPerformed(evt));

        deleteProjectButton.setText("Delete Project");
        deleteProjectButton.addActionListener(evt -> deleteProjectButtonActionPerformed(evt));

        projectList.setModel(new javax.swing.DefaultComboBoxModel<>(projectNames.toArray(new String[0]))); //COPY THIS (sets combobox contents to proj array)
        projectList.addActionListener(evt -> projectListActionPerformed(evt));

        createTeamButton.setText("Create Team");
        createTeamButton.addActionListener(evt -> createTeamButtonActionPerformed(evt));

        deleteTeamButton.setText("Delete Team");
        deleteTeamButton.addActionListener(evt -> deleteTeamButtonActionPerformed(evt));

        teamList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        teamList.addActionListener(evt -> teamListActionPerformed(evt));

        manageProjectButton.setText("Manage Project");
        manageProjectButton.addActionListener(evt -> manageProjectButtonActionPerformed(evt));

        projectListLabel.setText("Project List");

        teamListLabel.setText("Team List");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(teamList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(projectList, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(createProjectButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                                                        .addComponent(createTeamButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(deleteTeamButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(deleteProjectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(manageProjectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(projectListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(teamListLabel))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(projectListLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(projectList, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(manageProjectButton))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(createProjectButton)
                                        .addComponent(deleteProjectButton))
                                .addGap(33, 33, 33)
                                .addComponent(teamListLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teamList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(deleteTeamButton)
                                        .addComponent(createTeamButton))
                                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>

    private void createProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String name = JOptionPane.showInputDialog("Enter project name.");
        if(name == null){return;} //return if cancel is pressed
        Project newProject = new Project(name);
        newProject.addTask("FirstTask");
        System.out.println(newProject.getTasks());

        System.out.println("Project name: "+newProject.getName());
    }

    private void deleteProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void createTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {
        TeamForm team = new TeamForm();
        // TODO add your handling code here:
    }

    private void deleteTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void teamListActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void projectListActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void manageProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Project selectedProj = projects.get(projectList.getSelectedItem().toString());
        ProjectForm project = new ProjectForm(selectedProj);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton createProjectButton;
    private javax.swing.JButton createTeamButton;
    private javax.swing.JButton deleteProjectButton;
    private javax.swing.JButton deleteTeamButton;
    private javax.swing.JButton manageProjectButton;
    private javax.swing.JComboBox<String> projectList;
    private javax.swing.JLabel projectListLabel;
    private javax.swing.JComboBox<String> teamList;
    private javax.swing.JLabel teamListLabel;

    // End of variables declaration
}
