/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;

/**
 *
 * @author joshu
 */
public class TeamForm extends javax.swing.JFrame {

    /**
     * Creates new form TeamForm
     */
    public TeamForm() {
        super("Team Manager");
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {


        jTextArea1 = new javax.swing.JTextArea();
        staffList = new javax.swing.JComboBox<>();
        addAsMemberButton = new javax.swing.JButton();
        addAsLeaderButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        teamNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        addStaffButton = new javax.swing.JButton();
        selectStaffLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        teamList = new javax.swing.JTextArea();



        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        staffList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        staffList.addActionListener(evt -> staffListActionPerformed(evt));

        addAsMemberButton.setText("Add as Member");
        addAsMemberButton.addActionListener(evt -> addAsMemberButtonActionPerformed(evt));

        addAsLeaderButton.setText("Add as Team Leader");
        addAsLeaderButton.addActionListener(evt -> addAsLeaderButtonActionPerformed(evt));

        finishButton.setText("Finalise Team");
        finishButton.addActionListener(evt -> finishButtonActionPerformed(evt));

        jLabel1.setText("Enter Team Name");

        addStaffButton.setText("Add Staff Member");
        addStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffButtonActionPerformed(evt);
            }
        });

        selectStaffLabel.setText("Select Staff Member");

        teamList.setEditable(false);
        teamList.setColumns(20);
        teamList.setRows(5);
        jScrollPane4.setViewportView(teamList);

        teamNameField.setText("⛧");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(staffList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(addAsLeaderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(addAsMemberButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(finishButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(addStaffButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                                        .addComponent(teamNameField)))
                                        .addComponent(selectStaffLabel))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(selectStaffLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staffList, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addAsLeaderButton)
                                        .addComponent(addAsMemberButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(teamNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(finishButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(addStaffButton))
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Team myTeam = new Team();
        myTeam.add("member1");
        myTeam.add("member2");
        myTeam.add("member3");
        Team myTeam2 = new Team();
        myTeam2.add("member1");
        myTeam2.add("member2");
        myTeam2.add("member3");
        System.out.println(Team.Companion.getMasterList().toString());

    }

    private void staffListActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addAsLeaderButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        addAsMemberButtonActionPerformed(evt);

    }

    private void addAsMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String oldText = teamList.getText();
        teamList.setText(oldText+staffList.getSelectedItem().toString()+"\n");
    }

    private void addStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton addAsLeaderButton;
    private javax.swing.JButton addAsMemberButton;
    private javax.swing.JButton addStaffButton;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel selectStaffLabel;
    private javax.swing.JComboBox<String> staffList;
    private javax.swing.JTextArea teamList;
    private javax.swing.JTextField teamNameField;
    // End of variables declaration
}
